### ISSUE TITLE
Cannot find blob with name: r1i

### ISSUE THREAD

**Issue by wangdazhong258** [meifannao/OpenVINO#1]
报错，不能生成新视频

**Comment by meifannao** [comment]
运行报错吗，可以发下截图

**Comment by wangdazhong258** [comment]
> 运行报错吗，可以发下截图
![1656994836(1)](https://user-images.githubusercontent.com/71005495/177248736-af47d36b-d99f-4ec3-ac80-56ce2b5d721f.png)

**Comment by meifannao** [comment]
> > 运行报错吗，可以发下截图
> > ![1656994836(1)](https://user-images.githubusercontent.com/71005495/177248736-af47d36b-d99f-4ec3-ac80-56ce2b5d721f.png)

https://github.com/meifannao/OpenVINO-RVM- 可以看看我新的仓库，这个应该没问题，所有源码都在里面，这个仓库用错模型了，使用方法是一样的

**Comment by wangdazhong258** [comment]
> 

可以执行并生成视频，但仍然有报错提示
![image](https://user-images.githubusercontent.com/71005495/177329916-789ddb95-d85a-4517-9f13-e7709488307b.png)

**Comment by meifannao** [comment]
> 


身为一名投身于计算机的有志青年，这种Warning我们一般直接忽略

**Comment by wangdazhong258** [comment]
好的
