### ISSUE TITLE
关于traincode

### ISSUE THREAD

**Issue by lblbk** [meifannao/OpenVINO#2]
打扰一下，根目录下的 `traincode` 文件没有内容啊，具体的onnx转换脚本作者大大可以简单说一下吗，是借用 defuth 大大的方式吗

**Comment by meifannao** [comment]
traincode代码当时没有上传上去，你可以我代码仓库里[OpenVINO-RVM-]里面有没有你想要的代码

**Comment by lblbk** [comment]
> traincode代码当时没有上传上去，你可以我代码仓库里[OpenVINO-RVM-]里面有没有你想要的代码

可能我表述不太清楚，我是想说 `onnx->openvino` 的代码
